### ISSUE TITLE
Check GitLab API error 404 after update to 6.5.1

### ISSUE THREAD

**Issue by braa2k** [cvut/gentoo-overlay#13]
I've just updated my 6.0.0-r2 with the fresh ebuild ver. 6.5.1. I'm glad to see fixes of previous version's bugs. Everything looks fine! But I've got strange error during gitlab:check, that I'd never meet with 6.0.0-r2:
```
Running /opt/APP/git/gitlab-shell/bin/check
Check GitLab API access: FAILED. code: 404
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /opt/APP/git/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.

Checking GitLab Shell ... Finished
```
As we can see from the message above, test procedure expects gitlab-shell instance in my git-user home. But according to the by-default installation of ebuild I've got different location for them:
/etc/gitlab-shell.yml  <-- config
/usr/share/gitlab-shell/ <-- scripts
Here is my gitlab:env:info output:
```
System information
System:         Gentoo n/a
Current User:   git
Using RVM:      no
Ruby Version:   1.9.3p484
Gem Version:    2.0.3
Bundler Version:1.3.5
Rake Version:   10.1.0

GitLab information
Version:        6.5.1
Revision:       eca0c4a
Directory:      /opt/gitlab-6
DB Adapter:     mysql2
URL:            https://my.gitlab.host
HTTP Clone URL: https://my.gitlab.host/some-project.git
SSH Clone URL:  git@my.gitlab.host:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.8.0
Repositories:   /opt/APP/git/repositories/
Hooks:          /usr/share/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by jirutka** [comment]
I don’t maintain ebuild for GitLab anymore, its new home is in the [fritteli’s overlay](https://github.com/fritteli/gentoo-overlay).
