### ISSUE TITLE
Could not find modernizr-2.6.2 in any of the sources

### ISSUE THREAD

**Issue by kybi** [cvut/gentoo-overlay#16]
>>> Emerging (1 of 1) www-apps/gitlabhq-6.5.1-r1 from cvut
 * gitlabhq-6.5.1.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                  [ ok ]
>>> Unpacking source...
>>> Unpacking gitlabhq-6.5.1.tar.gz to /var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/work/all
>>> Source unpacked in /var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/work
>>> Preparing source in /var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/work ...
 * Running prepare phase for all ...
 * Applying gitlabhq-6.5.1-fix-gemfile.patch ...                                                                                               [ ok ]
 * Applying gitlabhq-6.5.1-fix-project-name-regex.patch ...                                                                                    [ ok ]
 * Applying gitlabhq-6.0.2-fix-sendmail-config.patch ...                                                                                       [ ok ]
 * Applying gitlabhq-6.5.1-fix-ldap-dn-case.patch ...                                                                                          [ ok ]
 * Applying gitlabhq-6.5.1-ldap-custom-mapping.patch ...                                                                                       [ ok ]
 * Applying gitlabhq-6.5.1-email-custom-reply_to.patch ...                                                                                     [ ok ]
 * Running source copy phase for ruby19 ...
 * Running source copy phase for ruby20 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/work ...
>>> Source compiled.
>>> Test phase [not enabled]: www-apps/gitlabhq-6.5.1-r1

>>> Install gitlabhq-6.5.1-r1 into /var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/image/ category www-apps
 * Running install phase for all ...
 * Running bundle install --deployment --without development test aws postgres ...
Fetching source index from https://rubygems.org/
Fetching https://github.com/brianmario/charlock_holmes.git
remote: Reusing existing pack: 824, done.
remote: Total 824 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (824/824), 34.65 MiB | 5.03 MiB/s, done.
Resolving deltas: 100% (411/411), done.
Fetching https://github.com/gitlabhq/markup.git
remote: Counting objects: 1024, done.
remote: Compressing objects: 100% (548/548), done.
remote: Total 1024 (delta 367), reused 1024 (delta 367)
Receiving objects: 100% (1024/1024), 147.02 KiB | 0 bytes/s, done.
Resolving deltas: 100% (367/367), done.
Fetching https://github.com/jirutka/omniauth-ldap.git
remote: Counting objects: 360, done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 360 (delta 113), reused 360 (delta 113)
Receiving objects: 100% (360/360), 108.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (113/113), done.
Could not find modernizr-2.6.2 in any of the sources
 * ERROR: www-apps/gitlabhq-6.5.1-r1::cvut failed (install phase):
 *   bundler failed
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_install
 *   environment, line 7167:  Called ruby-ng_src_install
 *   environment, line 6936:  Called _ruby_invoke_environment 'all' 'all_ruby_install'
 *   environment, line 1076:  Called all_ruby_install
 *   environment, line 1152:  Called die
 * The specific snippet of code:
 *       ${RUBY} /usr/bin/bundle install ${bundle_args} || die "bundler failed";
 * 
 * If you need support, post the output of `emerge --info '=www-apps/gitlabhq-6.5.1-r1::cvut'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/gitlabhq-6.5.1-r1::cvut'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME=""
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =gitlabhq-6.5.1
 * The complete build log is located at '/var/log/portage/www-apps:gitlabhq-6.5.1-r1:20140404-110010.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/image/opt/gitlab-6'
 * S: '/var/tmp/portage/www-apps/gitlabhq-6.5.1-r1/work/all/gitlabhq-6.5.1'

>>> Failed to emerge www-apps/gitlabhq-6.5.1-r1, Log file:

>>>  '/var/log/portage/www-apps:gitlabhq-6.5.1-r1:20140404-110010.log'

**Comment by jirutka** [comment]
I don’t maintain ebuild for GitLab anymore, its new home is in the [fritteli’s overlay](https://github.com/fritteli/gentoo-overlay).
